global:
  fetch:
    interval: PT10S

fetches:
  taskName: task1
  target: http://localhost:8081
  path: /actuator/prometheus

tsdb:
  metricSecondsTtl: P30D
  metricMinutesTtl: P30D
  metricHoursTtl: P30D
