global_config:
  tsdb_config:
    metric_seconds_ttl: PT5M
    metric_minutes_ttl: PT10M
    metric_hours_ttl: PT15M
  fetch_config:
    interval: PT30S
    timeout: 123
  requests_config:
    headers:
      Accept: application/json
      Connection: keep-alive
    params:
      param_name1: param_value1
  notification_rules_config:
    - name: system_cpu_usage
      condition: ">0"
      flags:
        - "cpu usage"
        - "alarm!!!!"
      annotation: "This message notify you about your service. Cpu usage more than 0. Its scared!"


tasks_config:
  - task_name: task1
    target: http://45.142.213.160:9091
    path: /

alerting_config:
  host: http://62.84.114.36:8084
  path: /
  timeout: 123

server:
  port: 8080