global_config:
  tsdb_config:
    metric_seconds_ttl: PT5M
    metric_minutes_ttl: PT10M
    metric_hours_ttl: PT15M
  fetch_config:
    interval: PT30S
    timeout: 123
  requests_config:
    headers:
      Accept: application/json
      Connection: keep-alive
    params:
      param_name1: param_value1
  notification_rules_config:
    - name: system_cpu_usage
      condition: ">0"
      flags:
        - flag1
        - flag2
      annotation: hello from jargus


tasks_config:
  - task_name: task1
    target: http://host.docker.internal:9090
    path: /

alerting_config:
  host: http://host.docker.internal:8081
  path: /
  timeout: 123

server:
  port: 8081