global_config:
  tsdb_config: # Settings to database
    metric_seconds_ttl: P30D # Time to live metrics with second interval
    metric_minutes_ttl: P30D # Time to live metrics with minutes interval
    metric_hours_ttl: P30D # Time to live metrics with hours interval
  fetch_config:
    interval: PT10S
    timeout: 123
